name: sylius 

type: php:5.6
build:
  flavor: symfony

relationships:
    database: 'mysql:mysql'

web:
    document_root: '/web'
    passthru: '/app.php'

disk: 2048

mounts:
    '/var/cache': 'shared:files/cache'
    '/var/logs': 'shared:files/logs'

hooks:
    build: |
      rm web/app_dev.php
      app/console --env=prod assetic:dump --no-debug
    deploy: |
      app/console --env=prod cache:clear --no-debug
